CREATE TABLE REST_EMPLOYEES (
    EmployeeID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    EmployeeName VARCHAR2(100) NOT NULL,
    Role VARCHAR2(50) NOT NULL,
    HireDate DATE NOT NULL,
    CONSTRAINT pk_rest_employees PRIMARY KEY (EmployeeID)
);

CREATE TABLE REST_CUSTOMERS (
    CustomerID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    CustomerName VARCHAR2(100) NOT NULL,
    Phone VARCHAR2(20),
    Email VARCHAR2(100),
    CONSTRAINT pk_rest_customers PRIMARY KEY (CustomerID),
    CONSTRAINT uq_rest_customers_phone UNIQUE (Phone),
    CONSTRAINT uq_rest_customers_email UNIQUE (Email)
);

CREATE TABLE REST_DINING_TABLES (
    TableID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    TableLabel VARCHAR2(20) NOT NULL,
    Capacity NUMBER NOT NULL,
    Status VARCHAR2(20) NOT NULL,
    CONSTRAINT pk_rest_dining_tables PRIMARY KEY (TableID),
    CONSTRAINT uq_rest_dining_tables_label UNIQUE (TableLabel),
    CONSTRAINT chk_rest_dining_tables_capacity CHECK (Capacity > 0),
    CONSTRAINT chk_rest_dining_tables_status CHECK (
        Status IN ('AVAILABLE', 'OCCUPIED', 'RESERVED')
    )
);

CREATE TABLE REST_MENU_CATEGORIES (
    CategoryID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    CategoryName VARCHAR2(50) NOT NULL,
    CONSTRAINT pk_rest_menu_categories PRIMARY KEY (CategoryID),
    CONSTRAINT uq_rest_menu_categories_name UNIQUE (CategoryName)
);

CREATE TABLE REST_MENU_ITEMS (
    ItemID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    CategoryID NUMBER NOT NULL,
    ItemName VARCHAR2(100) NOT NULL,
    Price NUMBER(8,2) NOT NULL,
    IsAvailable CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT pk_rest_menu_items PRIMARY KEY (ItemID),
    CONSTRAINT fk_rest_menu_items_category
        FOREIGN KEY (CategoryID) REFERENCES REST_MENU_CATEGORIES(CategoryID),
    CONSTRAINT uq_rest_menu_items_name UNIQUE (ItemName),
    CONSTRAINT chk_rest_menu_items_price CHECK (Price > 0),
    CONSTRAINT chk_rest_menu_items_available CHECK (IsAvailable IN ('Y', 'N'))
);

CREATE TABLE REST_ORDERS (
    OrderID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    CustomerID NUMBER NOT NULL,
    EmployeeID NUMBER NOT NULL,
    TableID NUMBER,
    OrderType VARCHAR2(20) NOT NULL,
    OrderStatus VARCHAR2(20) NOT NULL,
    OrderDateTime DATE NOT NULL,
    Notes VARCHAR2(200),
    CONSTRAINT pk_rest_orders PRIMARY KEY (OrderID),
    CONSTRAINT fk_rest_orders_customer
        FOREIGN KEY (CustomerID) REFERENCES REST_CUSTOMERS(CustomerID),
    CONSTRAINT fk_rest_orders_employee
        FOREIGN KEY (EmployeeID) REFERENCES REST_EMPLOYEES(EmployeeID),
    CONSTRAINT fk_rest_orders_table
        FOREIGN KEY (TableID) REFERENCES REST_DINING_TABLES(TableID),
    CONSTRAINT chk_rest_orders_type CHECK (OrderType IN ('DINE_IN', 'TAKEOUT')),
    CONSTRAINT chk_rest_orders_status CHECK (
        OrderStatus IN ('OPEN', 'PREPARING', 'READY', 'SERVED', 'PAID', 'CANCELLED')
    )
);

CREATE TABLE REST_TAKEOUT_ORDERS (
    OrderID NUMBER NOT NULL,
    PickupName VARCHAR2(100) NOT NULL,
    PickupPhone VARCHAR2(20) NOT NULL,
    PickupTime DATE NOT NULL,
    CONSTRAINT pk_rest_takeout_orders PRIMARY KEY (OrderID),
    CONSTRAINT fk_rest_takeout_orders_order
        FOREIGN KEY (OrderID) REFERENCES REST_ORDERS(OrderID)
);

CREATE TABLE REST_ORDER_ITEMS (
    OrderItemID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    OrderID NUMBER NOT NULL,
    ItemID NUMBER NOT NULL,
    Quantity NUMBER NOT NULL,
    UnitPrice NUMBER(8,2) NOT NULL,
    SpecialRequest VARCHAR2(200),
    CONSTRAINT pk_rest_order_items PRIMARY KEY (OrderItemID),
    CONSTRAINT fk_rest_order_items_order
        FOREIGN KEY (OrderID) REFERENCES REST_ORDERS(OrderID),
    CONSTRAINT fk_rest_order_items_item
        FOREIGN KEY (ItemID) REFERENCES REST_MENU_ITEMS(ItemID),
    CONSTRAINT chk_rest_order_items_quantity CHECK (Quantity > 0),
    CONSTRAINT chk_rest_order_items_unitprice CHECK (UnitPrice >= 0)
);

CREATE TABLE REST_PAYMENTS (
    PaymentID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    OrderID NUMBER NOT NULL,
    PaymentMethod VARCHAR2(20) NOT NULL,
    Amount NUMBER(10,2) NOT NULL,
    CONSTRAINT pk_rest_payments PRIMARY KEY (PaymentID),
    CONSTRAINT fk_rest_payments_order
        FOREIGN KEY (OrderID) REFERENCES REST_ORDERS(OrderID),
    CONSTRAINT chk_rest_payments_method CHECK (
        PaymentMethod IN ('CASH', 'CARD', 'ONLINE')
    ),
    CONSTRAINT chk_rest_payments_amount CHECK (Amount >= 0)
);
